export const Key = {
  Space: ' ',
  Escape: 'Escape',
  Enter: 'Enter',
  Backslash: '\\',
  Delete: 'Delete',
  Backspace: 'Backspace',
  Tab: 'Tab',
  ArrowUp: 'ArrowUp',
  ArrowDown: 'ArrowDown',
  ArrowLeft: 'ArrowLeft',
  ArrowRight: 'ArrowRight',
  Equal: '=',
  Minus: '-',
  Slash: '/',
  A: 'a',
  C: 'c',
  D: 'd',
  E: 'e',
  G: 'g',
  I: 'i',
  J: 'j',
  M: 'm',
  O: 'o',
  Q: 'q',
  R: 'r',
  S: 's',
  V: 'v',
  Z: 'z',
  Zero: '0',
  One: '1',
  Two: '2',
  Three: '3',
  Four: '4',
  Five: '5',
} as const;
